# Generated by Django 5.0.7 on 2024-07-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveSmallIntegerField()),
                ('teacher_id', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('salary', models.PositiveBigIntegerField()),
                ('specializiation', models.TextField()),
                ('hire_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('bio', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='')),
                ('course_code', models.PositiveSmallIntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
