# Generated by Django 5.0.7 on 2024-07-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_photo',
            new_name='profile',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specializiation',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.BigIntegerField(),
        ),
    ]
