# Generated by Django 5.0.7 on 2024-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_rename_teacher_id_teacher_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.CharField(default='python', max_length=20),
        ),
    ]
