# Generated by Django 5.0.7 on 2024-07-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_teacher_age_teacher_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student_id',
            new_name='student_name',
        ),
    ]
