# Generated by Django 5.0.7 on 2024-07-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_rename_student_id_teacher_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student_name',
            new_name='course_code',
        ),
    ]
