# Generated by Django 5.0.7 on 2024-07-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        ('student', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='student',
        ),
        migrations.AlterField(
            model_name='classes',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
