# Generated by Django 5.0.7 on 2024-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=20)),
                ('course_category', models.TextField()),
                ('course_start_date', models.DateField()),
                ('course_end_date', models.DateField()),
                ('course_code', models.PositiveSmallIntegerField()),
                ('teacher_code', models.PositiveSmallIntegerField()),
                ('student_code', models.PositiveSmallIntegerField()),
                ('student_number', models.PositiveSmallIntegerField()),
                ('course_fee', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
