# Generated by Django 5.0.7 on 2024-07-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('student', '0003_alter_student_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='student_id',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_category',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='student_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
