# Generated by Django 5.0.7 on 2024-07-17 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('code', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveSmallIntegerField()),
                ('country', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('next_of_kin', models.CharField(max_length=20)),
                ('bio', models.TextField()),
                ('pic', models.ImageField(upload_to='')),
                ('course_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.courses')),
            ],
        ),
    ]
